name: EldenRingUHC
version: 1.1
main: main.main
api-version: 1.18 # Ajouter cette ligne
description: Un plugin UHC inspiré d'Elden Ring

commands:
  sethote:
    description: Définit l'hôte du UHC.
    usage: /sethote <joueur>
    permission: op

  stopuhc:
    description: Permet d'utiliser la commande /stopuhc.
    usage: /stopuhc
    permission: op

  confirmstuff:
    description: Commande pour sauvegarder l'inventaire.
    usage: /confirmstuff
    permission: op

  melina_grace:
      description: Vérifie si un joueur est guidé par la grâce.
      usage: /melina_grace <nom_du_joueur>
