name: EldenRingUHC
version: 1.1
main: main.main

commands:
  sethote:
    description: Définit l'hôte du UHC.
    usage: /sethote <joueur>
    permission: op

  stopuhc:
    description: Permet d'utiliser la commande /stopuhc.
    usage: /stopuhc
    permission: op

  confirmstuff:
    description: Commande pour sauvegarder l'inventaire.
    usage: /confirmstuff
    permission: op
